### PR TITLE
Resolve `NoMethodError` when using `Rack::Static` with rack >= 2.1.0

### PR DESCRIPTION
**Pull request by rmacklin**
The `Rack::VCR::Transaction#vcr_response` method was assuming that `@res.body` would respond to the `join` method:
https://github.com/miyagawa/rack-vcr/blob/7481071b2fb291c089d0c7f507b67775bbf0364d/lib/rack/vcr/transaction.rb#L32
This worked when used with rack < 2.1.0, but it wasn't part of the rack spec. According to the spec, `body` only needs to respond to `each` and yield String values:
https://github.com/rack/rack/blame/026537fbe8baa9a9ac71417815b5be26fc28da4f/SPEC.rdoc#L266-L267

The assumption that it would respond to `join` was broken by https://github.com/rack/rack/commit/8c62821f4a464858a6b6ca3c3966ec308d2bb53e (https://github.com/rack/rack/pull/1434) which was released in rack 2.1.0. In rack 2.1.0 and beyond, when we request a file that's served by the `Rack::Static` middleware, the `Rack::Response#body` will be a `Rack::Files::Iterator`, which does not respond to `join`. As a result, a `NoMethodError` would be raised from the above line in `Rack::VCR::Transaction#vcr_response`. The test added in https://github.com/miyagawa/rack-vcr/commit/59397ea701c5c28fec0cbbfcda0ac25f3bac891a fails with that error when executed on rack >= 2.1.0 without applying the corresponding change in `transaction.rb`:
```
  with Rack::Static
    runs the HTTP request (FAILED - 1)

Failures:

  1) Rack::VCR with Rack::Static runs the HTTP request
     Failure/Error: @res.body.join(''),

     NoMethodError:
       undefined method `join' for #<Rack::Files::Iterator:0x00007f8a534d7ee0>
       ./lib/rack/vcr/transaction.rb:32:in `vcr_response'
       ./lib/rack/vcr/transaction.rb:10:in `capture'
       ./lib/rack/vcr.rb:33:in `run_request'
       ./lib/rack/vcr.rb:20:in `call'
```

To fix the error, we've ensured that we'll invoke `join` on an `Array` (since that will respond to `join`) by simply changing `@res.body` to `@res.body.to_enum.to_a`.

Note: This is branched off https://github.com/miyagawa/rack-vcr/pull/9 since that includes the necessary changes for running our test suite against multiple versions of rack. The fix itself (https://github.com/miyagawa/rack-vcr/commit/59397ea701c5c28fec0cbbfcda0ac25f3bac891a) is independent, but it seemed appropriate to do it in this order.

### CODE REVIEW

**Comment by miyagawa** [comment]
`to_enum` is also not part of the Rack spec, no?

**Comment by rmacklin** [comment]
`to_enum` is part of the `Object` interface:
https://ruby-doc.org/core-2.4.10/Object.html#method-i-to_enum

**Comment by miyagawa** [comment]
I see, and it defaults to call `each` on the object. Thanks!
